### ISSUE TITLE
Init fails with TypeError: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by THPubs** [kodeflex/wp-artisan#26]
The initialization process fails with the following error:

    /home/pubudu/Learning/wp-artisan/lib/actions/artisan.js:154
                        message: resp.message
                                     ^

    TypeError: Cannot read property 'message' of null
        at wpCli.call (/home/pubudu/Learning/wp-artisan/lib/actions/artisan.js:154:34)
        at /home/pubudu/Learning/wp-artisan/node_modules/node-wp-cli/lib/index.js:45:9
        at /home/pubudu/Learning/wp-artisan/node_modules/shelljs/src/exec.js:204:9
        at ChildProcess.exithandler (child_process.js:212:5)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:194:7)
        at maybeClose (internal/child_process.js:899:16)
        at Socket.<anonymous> (internal/child_process.js:342:11)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:191:7)

Upon further investigation, it looks like wp-cli throws the following error at `artisan.js:148`:

    err { name: 'Error',
      code: 1,
      message: 'Error: Too many positional arguments: API\n' }

**Comment by kasunben** [comment]
@THPubs Will take a look. Seems like `WP-CLI` failing because of some reason.

**Comment by THPubs** [comment]
Yeap. Perhaps the tool have changed?

**Comment by kasunben** [comment]
@THPubs anyway, will do a hotfix for this, so we can do a release.

**Comment by kasunben** [comment]
@THPubs I tried several ways but couldn't re-produce the issue. :(.
Anyway I handled the `resp.message` in case something goes wrong.

**Comment by THPubs** [comment]
Hmmm. I'll also do some more tests and see :smile:

**Comment by kasunben** [comment]
This issue was moved to 99xt/wp-artisan#15
