### ISSUE TITLE
If the install script is skipped, wp serve fails

### ISSUE THREAD

**Issue by THPubs** [kodeflex/wp-artisan#27]
Wp serve fails if the installation script is skipped because `wp serve` try to modify the port in the database and if we don't run the install script, there are no tables in the database.

**Comment by THPubs** [comment]
Just found out that the issue is not there in the `dev` branch :smile: It works well. I just improved it's error message and made a pull request. But the released version of the package is failing!

**Comment by kasunben** [comment]
@THPubs Ah!, Let's release minor fix version then.

**Comment by THPubs** [comment]
Perfect!

**Comment by kasunben** [comment]
Published v0.0.3.

**Comment by kasunben** [comment]
This issue was moved to 99xt/wp-artisan#16
