### ISSUE TITLE
wp init [Path] error

### ISSUE THREAD

**Issue by asela-wijesinghe** [kodeflex/wp-artisan#29]
if we use 
`wp init "My WordPress Site" `
in this manner as mentioned in the docs, an error is shown 

    Initializing...
    Creating directory structure '/home/azeela/Projects/My WordPress Site'.
    ✖  Fetching WordPress latest release... failed.

**Comment by kasunben** [comment]
@asela-wijesinghe I think I figured out what going wrong here. `WP-CLI` may prevents kind of uses. Seems like it's possible to fix easily. Thanks! for reporting. :)

**Comment by asela-wijesinghe** [comment]
Cheers :)

**Comment by kasunben** [comment]
Earlier we used our own implementation to fetching and installing WordPress in local env. Seems like it has missed to test after moved the logic with `WP-CLI`, Time to write test cases :D

**Comment by kasunben** [comment]
Fixed #31

**Comment by kasunben** [comment]
This issue was moved to 99xt/wp-artisan#17
