### ISSUE TITLE
Improve the init prompt

### ISSUE THREAD

**Issue by THPubs** [kodeflex/wp-artisan#6]
Some suggestions to improve the prompt :

- [x]  Change the type of password prompts to `password` instead of plain input.
- [ ]  Change the default value of `MYSQL Database Table Prefix` to something else. (https://digwp.com/2010/10/change-database-prefix/) It is highly recommended that we use a different prefix for improved security. Perhaps a randomly generated string?
- [ ] Change the default `adminUser` to something else for security.
- [ ]  Change the default admin password. Optional.

**Comment by kasunben** [comment]
@THPubs 
> Change the type of password prompts to password instead of plain input.

yep. let's change it. :)

> Change the default value of MYSQL Database Table Prefix to something else. 

My suggestion is, keep them as it is in the development at the first. But, In the deployment, we can force to change them if those configs are still set to defaults.

The thing is, sometimes, developer need to quick setup for just for test works.

**Comment by THPubs** [comment]
@thinkholic Agreed! I will check the type change in a bit...

**Comment by kasunben** [comment]
This issue was moved to 99xt/wp-artisan#7
